apiVersion: v1
kind: Service
metadata:
  name: kustomize-demo-app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: kustomize-demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kustomize-demo-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kustomize-demo-app
    spec:
      containers:
      - env:
        - name: CUSTOM_ENV_VARIABLE
          value: Value defined by Kustomize ❤️
        image: hello-world:latest
        name: app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
