apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-demo-app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: kustomize-demo-app
                  key: db.password