apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-demo-app
spec:
  selector:
    matchLabels:
      app: kustomize-demo-app
  template:
    metadata:
      labels:
        app: kustomize-demo-app
    spec:
      containers:
        - name: app
          image: hello-world:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP